theme: jekyll-theme-minimal
title: daniel.xyz
description: [quick info and blogposts]
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/NecessaryForm"
